# Generated by Django 6.0.2 on 2026-02-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='deleted_at',
            field=models.BooleanField(default=False),
        ),
    ]
