# Generated by Django 6.0.2 on 2026-02-21 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_post_deleted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='deleted_at',
            new_name='is_deleted',
        ),
    ]
